FROM golang:1.23-alpine3.19

ENV GOPATH=/
RUN go env -w GOCACHE=/.cache

COPY ./ ./

RUN go mod download -x
RUN --mount=type=cache,target=/.cache go build -v -o auth-service ./cmd/auth-service

CMD ["./auth-service"]