version: '3.8'

services:
  newella-db:
    image: postgres:17.0-alpine3.20
    container_name: newella-db
    restart: unless-stopped
    volumes:
      - newella_db_tmp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 31032003
      POSTGRES_DB: newella-db
    expose:
      - 5433
    command: -p 5433
    networks:
      - appnet

volumes:
  newella_db_tmp:

networks:
  appnet:
    name: appnet
    driver: bridge